<?php

namespace S246109\BeatMagazine\Controllers;

use S246109\BeatMagazine\Models\Album;
use S246109\BeatMagazine\Models\Song;

class AlbumsController
{

    public function index()
    {
        $albums = self::getAllAlbums();


        include __DIR__ . '/../Views/albums.php';
    }

    public static function getAllAlbums()
    {
        // This could retrieve data from a database; here we use static data for demonstration
        return [
            new Album(
                "/images/baitones.jpg",
                "Leak 04-13 (Bait Ones)",
                "Jai Paul",
                "Electronic",
                "XL Recordings",
                4.5,
                4.8,
                "2019-06-01",
                [
                    new Song(1, "One of the Bredrins", "0:10"),
                    new Song(2, "Str8 Outta Mumbai", "2:42"),
                    new Song(3, "Zion Wolf Theme (Unfinished)", "3:07"),
                    new Song(4, "Garden of Paradise (Instrumental, Unfinished)", "1:16"),
                    new Song(5, "Genevieve (Unfinished)", "3:57"),
                    new Song(6, "Raw Beat (Unfinished)", "0:29"),
                    new Song(7, "Crush (Unfinished)", "3:45"),
                    new Song(8, "Good Time", "0:27"),
                    new Song(9, "Jasmine (Demo)", "4:13"),
                    new Song(10, "100,000 (Unfinished)", "2:55"),
                    new Song(11, "Vibin' (Unfinished)", "2:43"),
                    new Song(12, "Baby Beat (Unfinished)", "0:40"),
                    new Song(13, "Desert River (Unfinished)", "3:05"),
                    new Song(14, "Chix (Unfinished)", "0:56"),
                    new Song(15, "All Night (Unfinished)", "3:12"),
                    new Song(16, "BTSTU (Demo)", "3:30"),
                ]
            ),
            new Album(
                "/images/brat.png",
                "Brat",
                "Charli XCX",
                "Pop",
                "Asylum Records",
                4.2,
                4.7,
                "2024-06-07",
                [
                    new Song(1, "360", "4:25"),
                    new Song(2, "Club Classics", "2:39"),
                    new Song(3, "Sympathy Is a Knife", "2:37"),
                    new Song(4, "I Might Say Something Stupid", "1:55"),
                    new Song(5, "Talk Talk", "2:52"),
                    new Song(6, "Von Dutch", "3:34"),
                    new Song(7, "Everything Is Romantic", "3:30"),
                    new Song(8, "Rewind", "3:00"),
                    new Song(9, "So I", "3:37"),
                    new Song(10, "Girl, So Confusing", "3:06"),
                    new Song(11, "Apple", "2:35"),
                    new Song(12, "B2B", "3:04"),
                    new Song(13, "Mean Girls", "3:19"),
                    new Song(14, "I Think About It All the Time", "2:23"),
                    new Song(15, "365", "3:34"),
                ]
            ),
            new Album(
                "/images/100%-Electronica.jpg",
                "100% Electronica",
                "George Clanton",
                "Electronica",
                "100% Electronica",
                4.6,
                4.9,
                "2015-11-02",
                [
                    new Song(1, "Never Late Again", "3:50"),
                    new Song(2, "Keep a Secret", "4:31"),
                    new Song(3, "Did I Flounder?", "3:56"),
                    new Song(4, "Bleed", "4:00"),
                    new Song(5, "Wonder Gently", "4:00"),
                    new Song(6, "Warmspot", "4:00"),
                    new Song(7, "It Makes the Babies Want to Cry", "4:00"),
                    new Song(8, "Innocence", "4:00"),
                    new Song(9, "Kill You in Bed", "4:00"),
                    new Song(10, "Pure in the Night", "4:00"),
                ]
            ),
            new Album(
                "/images/am-ovlov.jpg",
                "Am",
                "Ovlov",
                "Indie Rock",
                "Exploding In Sound",
                4.0,
                4.3,
                "2013-07-02",
                [
                    new Song(1, "Grapes", "3:50"),
                    new Song(2, "Where's My Dini?", "4:31"),
                    new Song(3, "The Well", "3:56"),
                    new Song(4, "Moth Rock", "4:00"),
                    new Song(5, "There's My Dini!", "4:00"),
                    new Song(6, "Blue Baby", "4:00"),
                    new Song(7, "The Great Crocodile", "4:00"),
                    new Song(8, "Nu Punk", "4:00"),
                ]
            ),
            new Album(
                "/images/s.jpg",
                "s",
                "they are gutting a body of water",
                "Shoegaze",
                "Run For Cover Records",
                4.3,
                4.5,
                "2020-10-09",
                [
                    new Song(1, "Kmart Amen Break", "3:50"),
                    new Song(2, "Cold in the Rain", "4:31"),
                    new Song(3, "A Man I’ll Never Be", "3:56"),
                    new Song(4, "The Blackest of Hair", "4:00"),
                    new Song(5, "8ball", "4:00"),
                    new Song(6, "On Audiotree Live", "4:00"),
                    new Song(7, "Return to Earth", "4:00"),
                    new Song(8, "Seltzer", "4:00"),
                ]
            ),
            new Album(
                "/images/baitones.jpg",
                "Leak 04-13 (Bait Ones)",
                "Jai Paul",
                "Electronic",
                "XL Recordings",
                4.5,
                4.8,
                "2019-06-01",
                [
                    new Song(1, "One of the Bredrins", "0:10"),
                    new Song(2, "Str8 Outta Mumbai", "2:42"),
                    new Song(3, "Zion Wolf Theme (Unfinished)", "3:07"),
                    new Song(4, "Garden of Paradise (Instrumental, Unfinished)", "1:16"),
                    new Song(5, "Genevieve (Unfinished)", "3:57"),
                    new Song(6, "Raw Beat (Unfinished)", "0:29"),
                    new Song(7, "Crush (Unfinished)", "3:45"),
                    new Song(8, "Good Time", "0:27"),
                    new Song(9, "Jasmine (Demo)", "4:13"),
                    new Song(10, "100,000 (Unfinished)", "2:55"),
                    new Song(11, "Vibin' (Unfinished)", "2:43"),
                    new Song(12, "Baby Beat (Unfinished)", "0:40"),
                    new Song(13, "Desert River (Unfinished)", "3:05"),
                    new Song(14, "Chix (Unfinished)", "0:56"),
                    new Song(15, "All Night (Unfinished)", "3:12"),
                    new Song(16, "BTSTU (Demo)", "3:30"),
                ]
            ),
            new Album(
                "/images/brat.png",
                "Brat",
                "Charli XCX",
                "Pop",
                "Asylum Records",
                4.2,
                4.7,
                "2024-06-07",
                [
                    new Song(1, "360", "4:25"),
                    new Song(2, "Club Classics", "2:39"),
                    new Song(3, "Sympathy Is a Knife", "2:37"),
                    new Song(4, "I Might Say Something Stupid", "1:55"),
                    new Song(5, "Talk Talk", "2:52"),
                    new Song(6, "Von Dutch", "3:34"),
                    new Song(7, "Everything Is Romantic", "3:30"),
                    new Song(8, "Rewind", "3:00"),
                    new Song(9, "So I", "3:37"),
                    new Song(10, "Girl, So Confusing", "3:06"),
                    new Song(11, "Apple", "2:35"),
                    new Song(12, "B2B", "3:04"),
                    new Song(13, "Mean Girls", "3:19"),
                    new Song(14, "I Think About It All the Time", "2:23"),
                    new Song(15, "365", "3:34"),
                ]
            ),
            new Album(
                "/images/100%-Electronica.jpg",
                "100% Electronica",
                "George Clanton",
                "Electronica",
                "100% Electronica",
                4.6,
                4.9,
                "2015-11-02",
                [
                    new Song(1, "Never Late Again", "3:50"),
                    new Song(2, "Keep a Secret", "4:31"),
                    new Song(3, "Did I Flounder?", "3:56"),
                    new Song(4, "Bleed", "4:00"),
                    new Song(5, "Wonder Gently", "4:00"),
                    new Song(6, "Warmspot", "4:00"),
                    new Song(7, "It Makes the Babies Want to Cry", "4:00"),
                    new Song(8, "Innocence", "4:00"),
                    new Song(9, "Kill You in Bed", "4:00"),
                    new Song(10, "Pure in the Night", "4:00"),
                ]
            ),
            new Album(
                "/images/am-ovlov.jpg",
                "Am",
                "Ovlov",
                "Indie Rock",
                "Exploding In Sound",
                4.0,
                4.3,
                "2013-07-02",
                [
                    new Song(1, "Grapes", "3:50"),
                    new Song(2, "Where's My Dini?", "4:31"),
                    new Song(3, "The Well", "3:56"),
                    new Song(4, "Moth Rock", "4:00"),
                    new Song(5, "There's My Dini!", "4:00"),
                    new Song(6, "Blue Baby", "4:00"),
                    new Song(7, "The Great Crocodile", "4:00"),
                    new Song(8, "Nu Punk", "4:00"),
                ]
            ),
            new Album(
                "/images/s.jpg",
                "s",
                "they are gutting a body of water",
                "Shoegaze",
                "Run For Cover Records",
                4.3,
                4.5,
                "2020-10-09",
                [
                    new Song(1, "Kmart Amen Break", "3:50"),
                    new Song(2, "Cold in the Rain", "4:31"),
                    new Song(3, "A Man I’ll Never Be", "3:56"),
                    new Song(4, "The Blackest of Hair", "4:00"),
                    new Song(5, "8ball", "4:00"),
                    new Song(6, "On Audiotree Live", "4:00"),
                    new Song(7, "Return to Earth", "4:00"),
                    new Song(8, "Seltzer", "4:00"),
                ]
            ),
            new Album(
                "/images/baitones.jpg",
                "Leak 04-13 (Bait Ones)",
                "Jai Paul",
                "Electronic",
                "XL Recordings",
                4.5,
                4.8,
                "2019-06-01",
                [
                    new Song(1, "One of the Bredrins", "0:10"),
                    new Song(2, "Str8 Outta Mumbai", "2:42"),
                    new Song(3, "Zion Wolf Theme (Unfinished)", "3:07"),
                    new Song(4, "Garden of Paradise (Instrumental, Unfinished)", "1:16"),
                    new Song(5, "Genevieve (Unfinished)", "3:57"),
                    new Song(6, "Raw Beat (Unfinished)", "0:29"),
                    new Song(7, "Crush (Unfinished)", "3:45"),
                    new Song(8, "Good Time", "0:27"),
                    new Song(9, "Jasmine (Demo)", "4:13"),
                    new Song(10, "100,000 (Unfinished)", "2:55"),
                    new Song(11, "Vibin' (Unfinished)", "2:43"),
                    new Song(12, "Baby Beat (Unfinished)", "0:40"),
                    new Song(13, "Desert River (Unfinished)", "3:05"),
                    new Song(14, "Chix (Unfinished)", "0:56"),
                    new Song(15, "All Night (Unfinished)", "3:12"),
                    new Song(16, "BTSTU (Demo)", "3:30"),
                ]
            ),
            new Album(
                "/images/brat.png",
                "Brat",
                "Charli XCX",
                "Pop",
                "Asylum Records",
                4.2,
                4.7,
                "2024-06-07",
                [
                    new Song(1, "360", "4:25"),
                    new Song(2, "Club Classics", "2:39"),
                    new Song(3, "Sympathy Is a Knife", "2:37"),
                    new Song(4, "I Might Say Something Stupid", "1:55"),
                    new Song(5, "Talk Talk", "2:52"),
                    new Song(6, "Von Dutch", "3:34"),
                    new Song(7, "Everything Is Romantic", "3:30"),
                    new Song(8, "Rewind", "3:00"),
                    new Song(9, "So I", "3:37"),
                    new Song(10, "Girl, So Confusing", "3:06"),
                    new Song(11, "Apple", "2:35"),
                    new Song(12, "B2B", "3:04"),
                    new Song(13, "Mean Girls", "3:19"),
                    new Song(14, "I Think About It All the Time", "2:23"),
                    new Song(15, "365", "3:34"),
                ]
            ),
            new Album(
                "/images/100%-Electronica.jpg",
                "100% Electronica",
                "George Clanton",
                "Electronica",
                "100% Electronica",
                4.6,
                4.9,
                "2015-11-02",
                [
                    new Song(1, "Never Late Again", "3:50"),
                    new Song(2, "Keep a Secret", "4:31"),
                    new Song(3, "Did I Flounder?", "3:56"),
                    new Song(4, "Bleed", "4:00"),
                    new Song(5, "Wonder Gently", "4:00"),
                    new Song(6, "Warmspot", "4:00"),
                    new Song(7, "It Makes the Babies Want to Cry", "4:00"),
                    new Song(8, "Innocence", "4:00"),
                    new Song(9, "Kill You in Bed", "4:00"),
                    new Song(10, "Pure in the Night", "4:00"),
                ]
            ),
            new Album(
                "/images/am-ovlov.jpg",
                "Am",
                "Ovlov",
                "Indie Rock",
                "Exploding In Sound",
                4.0,
                4.3,
                "2013-07-02",
                [
                    new Song(1, "Grapes", "3:50"),
                    new Song(2, "Where's My Dini?", "4:31"),
                    new Song(3, "The Well", "3:56"),
                    new Song(4, "Moth Rock", "4:00"),
                    new Song(5, "There's My Dini!", "4:00"),
                    new Song(6, "Blue Baby", "4:00"),
                    new Song(7, "The Great Crocodile", "4:00"),
                    new Song(8, "Nu Punk", "4:00"),
                ]
            ),
            new Album(
                "/images/s.jpg",
                "s",
                "they are gutting a body of water",
                "Shoegaze",
                "Run For Cover Records",
                4.3,
                4.5,
                "2020-10-09",
                [
                    new Song(1, "Kmart Amen Break", "3:50"),
                    new Song(2, "Cold in the Rain", "4:31"),
                    new Song(3, "A Man I’ll Never Be", "3:56"),
                    new Song(4, "The Blackest of Hair", "4:00"),
                    new Song(5, "8ball", "4:00"),
                    new Song(6, "On Audiotree Live", "4:00"),
                    new Song(7, "Return to Earth", "4:00"),
                    new Song(8, "Seltzer", "4:00"),
                ]
            ), new Album(
                "/images/baitones.jpg",
                "Leak 04-13 (Bait Ones)",
                "Jai Paul",
                "Electronic",
                "XL Recordings",
                4.5,
                4.8,
                "2019-06-01",
                [
                    new Song(1, "One of the Bredrins", "0:10"),
                    new Song(2, "Str8 Outta Mumbai", "2:42"),
                    new Song(3, "Zion Wolf Theme (Unfinished)", "3:07"),
                    new Song(4, "Garden of Paradise (Instrumental, Unfinished)", "1:16"),
                    new Song(5, "Genevieve (Unfinished)", "3:57"),
                    new Song(6, "Raw Beat (Unfinished)", "0:29"),
                    new Song(7, "Crush (Unfinished)", "3:45"),
                    new Song(8, "Good Time", "0:27"),
                    new Song(9, "Jasmine (Demo)", "4:13"),
                    new Song(10, "100,000 (Unfinished)", "2:55"),
                    new Song(11, "Vibin' (Unfinished)", "2:43"),
                    new Song(12, "Baby Beat (Unfinished)", "0:40"),
                    new Song(13, "Desert River (Unfinished)", "3:05"),
                    new Song(14, "Chix (Unfinished)", "0:56"),
                    new Song(15, "All Night (Unfinished)", "3:12"),
                    new Song(16, "BTSTU (Demo)", "3:30"),
                ]
            ),
            new Album(
                "/images/brat.png",
                "Brat",
                "Charli XCX",
                "Pop",
                "Asylum Records",
                4.2,
                4.7,
                "2024-06-07",
                [
                    new Song(1, "360", "4:25"),
                    new Song(2, "Club Classics", "2:39"),
                    new Song(3, "Sympathy Is a Knife", "2:37"),
                    new Song(4, "I Might Say Something Stupid", "1:55"),
                    new Song(5, "Talk Talk", "2:52"),
                    new Song(6, "Von Dutch", "3:34"),
                    new Song(7, "Everything Is Romantic", "3:30"),
                    new Song(8, "Rewind", "3:00"),
                    new Song(9, "So I", "3:37"),
                    new Song(10, "Girl, So Confusing", "3:06"),
                    new Song(11, "Apple", "2:35"),
                    new Song(12, "B2B", "3:04"),
                    new Song(13, "Mean Girls", "3:19"),
                    new Song(14, "I Think About It All the Time", "2:23"),
                    new Song(15, "365", "3:34"),
                ]
            ),
            new Album(
                "/images/100%-Electronica.jpg",
                "100% Electronica",
                "George Clanton",
                "Electronica",
                "100% Electronica",
                4.6,
                4.9,
                "2015-11-02",
                [
                    new Song(1, "Never Late Again", "3:50"),
                    new Song(2, "Keep a Secret", "4:31"),
                    new Song(3, "Did I Flounder?", "3:56"),
                    new Song(4, "Bleed", "4:00"),
                    new Song(5, "Wonder Gently", "4:00"),
                    new Song(6, "Warmspot", "4:00"),
                    new Song(7, "It Makes the Babies Want to Cry", "4:00"),
                    new Song(8, "Innocence", "4:00"),
                    new Song(9, "Kill You in Bed", "4:00"),
                    new Song(10, "Pure in the Night", "4:00"),
                ]
            ),
            new Album(
                "/images/am-ovlov.jpg",
                "Am",
                "Ovlov",
                "Indie Rock",
                "Exploding In Sound",
                4.0,
                4.3,
                "2013-07-02",
                [
                    new Song(1, "Grapes", "3:50"),
                    new Song(2, "Where's My Dini?", "4:31"),
                    new Song(3, "The Well", "3:56"),
                    new Song(4, "Moth Rock", "4:00"),
                    new Song(5, "There's My Dini!", "4:00"),
                    new Song(6, "Blue Baby", "4:00"),
                    new Song(7, "The Great Crocodile", "4:00"),
                    new Song(8, "Nu Punk", "4:00"),
                ]
            ),
            new Album(
                "/images/s.jpg",
                "s",
                "they are gutting a body of water",
                "Shoegaze",
                "Run For Cover Records",
                4.3,
                4.5,
                "2020-10-09",
                [
                    new Song(1, "Kmart Amen Break", "3:50"),
                    new Song(2, "Cold in the Rain", "4:31"),
                    new Song(3, "A Man I’ll Never Be", "3:56"),
                    new Song(4, "The Blackest of Hair", "4:00"),
                    new Song(5, "8ball", "4:00"),
                    new Song(6, "On Audiotree Live", "4:00"),
                    new Song(7, "Return to Earth", "4:00"),
                    new Song(8, "Seltzer", "4:00"),
                ]
            ),
            new Album(
                "/images/baitones.jpg",
                "Leak 04-13 (Bait Ones)",
                "Jai Paul",
                "Electronic",
                "XL Recordings",
                4.5,
                4.8,
                "2019-06-01",
                [
                    new Song(1, "One of the Bredrins", "0:10"),
                    new Song(2, "Str8 Outta Mumbai", "2:42"),
                    new Song(3, "Zion Wolf Theme (Unfinished)", "3:07"),
                    new Song(4, "Garden of Paradise (Instrumental, Unfinished)", "1:16"),
                    new Song(5, "Genevieve (Unfinished)", "3:57"),
                    new Song(6, "Raw Beat (Unfinished)", "0:29"),
                    new Song(7, "Crush (Unfinished)", "3:45"),
                    new Song(8, "Good Time", "0:27"),
                    new Song(9, "Jasmine (Demo)", "4:13"),
                    new Song(10, "100,000 (Unfinished)", "2:55"),
                    new Song(11, "Vibin' (Unfinished)", "2:43"),
                    new Song(12, "Baby Beat (Unfinished)", "0:40"),
                    new Song(13, "Desert River (Unfinished)", "3:05"),
                    new Song(14, "Chix (Unfinished)", "0:56"),
                    new Song(15, "All Night (Unfinished)", "3:12"),
                    new Song(16, "BTSTU (Demo)", "3:30"),
                ]
            ),
            new Album(
                "/images/brat.png",
                "Brat",
                "Charli XCX",
                "Pop",
                "Asylum Records",
                4.2,
                4.7,
                "2024-06-07",
                [
                    new Song(1, "360", "4:25"),
                    new Song(2, "Club Classics", "2:39"),
                    new Song(3, "Sympathy Is a Knife", "2:37"),
                    new Song(4, "I Might Say Something Stupid", "1:55"),
                    new Song(5, "Talk Talk", "2:52"),
                    new Song(6, "Von Dutch", "3:34"),
                    new Song(7, "Everything Is Romantic", "3:30"),
                    new Song(8, "Rewind", "3:00"),
                    new Song(9, "So I", "3:37"),
                    new Song(10, "Girl, So Confusing", "3:06"),
                    new Song(11, "Apple", "2:35"),
                    new Song(12, "B2B", "3:04"),
                    new Song(13, "Mean Girls", "3:19"),
                    new Song(14, "I Think About It All the Time", "2:23"),
                    new Song(15, "365", "3:34"),
                ]
            ),
            new Album(
                "/images/100%-Electronica.jpg",
                "100% Electronica",
                "George Clanton",
                "Electronica",
                "100% Electronica",
                4.6,
                4.9,
                "2015-11-02",
                [
                    new Song(1, "Never Late Again", "3:50"),
                    new Song(2, "Keep a Secret", "4:31"),
                    new Song(3, "Did I Flounder?", "3:56"),
                    new Song(4, "Bleed", "4:00"),
                    new Song(5, "Wonder Gently", "4:00"),
                    new Song(6, "Warmspot", "4:00"),
                    new Song(7, "It Makes the Babies Want to Cry", "4:00"),
                    new Song(8, "Innocence", "4:00"),
                    new Song(9, "Kill You in Bed", "4:00"),
                    new Song(10, "Pure in the Night", "4:00"),
                ]
            ),
            new Album(
                "/images/am-ovlov.jpg",
                "Am",
                "Ovlov",
                "Indie Rock",
                "Exploding In Sound",
                4.0,
                4.3,
                "2013-07-02",
                [
                    new Song(1, "Grapes", "3:50"),
                    new Song(2, "Where's My Dini?", "4:31"),
                    new Song(3, "The Well", "3:56"),
                    new Song(4, "Moth Rock", "4:00"),
                    new Song(5, "There's My Dini!", "4:00"),
                    new Song(6, "Blue Baby", "4:00"),
                    new Song(7, "The Great Crocodile", "4:00"),
                    new Song(8, "Nu Punk", "4:00"),
                ]
            ),
            new Album(
                "/images/s.jpg",
                "s",
                "they are gutting a body of water",
                "Shoegaze",
                "Run For Cover Records",
                4.3,
                4.5,
                "2020-10-09",
                [
                    new Song(1, "Kmart Amen Break", "3:50"),
                    new Song(2, "Cold in the Rain", "4:31"),
                    new Song(3, "A Man I’ll Never Be", "3:56"),
                    new Song(4, "The Blackest of Hair", "4:00"),
                    new Song(5, "8ball", "4:00"),
                    new Song(6, "On Audiotree Live", "4:00"),
                    new Song(7, "Return to Earth", "4:00"),
                    new Song(8, "Seltzer", "4:00"),
                ]
            ),
        ];
    }
}